version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=gtszoffice
      - POSTGRES_PASSWORD=gtszoffice
      - POSTGRES_DB=gtszoffice
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432