# Generated by Django 2.1.4 on 2019-01-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180606_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1547899962.2607565, max_length=20, unique=True),
        ),
    ]
